kafka-consumer:
  topic: "sensor-data"
  cfg:
    bootstrap-servers: "kafka1:29092,kafka2:29093"
    group-id: "my_simple_consumer"
    enable-auto-commit: True
    auto-offset-reset: "earliest"

greenplum:
  host: "greenplum"
  dbname: "gpdb"
  user: "greenplum"
  password: "greenplum"
  port: "5432"
  table: "sensor_data" 
